### ISSUE TITLE
[Suggestion] RecipeType toString differs from Serializer name

### ISSUE THREAD

**Issue by kindlich** [Corail31/woodcutter#1]
Yesterday, someone asked me about how to add recipes to your woodcutting mod using CraftTweaker's new Datapack support feature.

While trying to help them I saw that your recipe serializer and your recipetype's toString method have different names.
While this is not necessarily enforced by forge, it breaks this support for our RecipeType feature in CrT.

Reason:
Your IRecipeType for Woodcutting's toString method returns "woodcutting" whereas the recipe type and the serializer are named "corail_woodcutter:woodcutting".
Since Crafttweaker tries to get the serializer from the recipetype's toString method, it relies on the two of them being the same.

It would be a simple fix on your end, so I wanted to ask you if there was a specific reason why you named them differently, and if not if you could change that?
https://github.com/Corail31/woodcutter/blob/5115ec08534192ffed3de43b1e80789d5a857d89/src/main/java/ovh/corail/woodcutter/registry/ModRecipeTypes.java#L12-L20

If you have any questions, feel free to reply here or to ask me on discord (Tag is kindlich#9060), or better join Jared's [Blamejared discord server](https://discord.blamejared.com), where the CrT stuff happens ^^

**Change scope:** Small, but it could be a breaking change!
**Minecraft Version:** 1.14.4
**Forge Version:** 28.1.113
**Corails Woodcutter Version:** 1.0.6 for 1.14.4

**Comment by Corail31** [comment]
Hi Kindlich and thanks for taking time to look for cross-mod compatibility.
The "toString" method was only a copy paste of the vanilla one that doesn't specify the domain in the string, but i'm going to change it now that i'm informed of this.

**Comment by kindlich** [comment]
I just saw that you alredy updated the version on CF.

I can close this issue then.
In case you are interested or someone wants it as reference later, this is a way to add recipes via CrT's JSON system:
```zs
import crafttweaker.api.item.IIngredient;
import crafttweaker.api.item.IItemStack;

function addWoodcuttingRecipe(name as string, input as IIngredient, output as IItemStack) as void{
	<recipetype:corail_woodcutter:woodcutting>.addJSONRecipe(name, {
	    ingredient: input,
	    result: output.registryName,
	    count: output.amount
    });
}


addWoodcuttingRecipe("recipe_by_json_1", <tag:minecraft:wool>, <item:minecraft:apple> * 3);
addWoodcuttingRecipe("recipe_by_json_2", <item:minecraft:iron_pickaxe>, <item:minecraft:diamond_pickaxe>);
```

This will work from CrT version 5.0.2 onwards (which to this date is not yet released, though)
![image](https://user-images.githubusercontent.com/10351787/72174593-6181b900-33da-11ea-9bc4-9c0713b750a5.png)
