### ISSUE TITLE
[1.15.2] Missing JEI Usage

### ISSUE THREAD

**Issue by TheUntamed** [Corail31/woodcutter#13]
The JEI Category for Woodcutter recipes is just applied to one of the Woodcutters (the Jacaranda Sawmill) That means if people want to see what can be crafted with a Woodcutter they first have to find the one that is integrated. Or they don't even search because they think there are no recipes.

![Screenshot_1](https://user-images.githubusercontent.com/48363903/79081232-d63afb00-7d1b-11ea-8fe3-12cc046d0af7.jpg)

**Comment by Corail31** [comment]
Can you give me some explanations about the steps to understand the trouble ? as the icon in JEI is only one random stack of woodcutters

**Comment by TheUntamed** [comment]
JEI allows to view how an item is made and for what it can be used. (Default hot keys: R for recipe and U for usage while hovering above the item)
But only 1 Woodcutter shows the usage. If you hover above the others and press U nothing is shown.
That would be like you can only see what you can craft with Planks if you hover above the oak planks but not above any other type of plank.

**Comment by Corail31** [comment]
![woodcutter_jei](https://user-images.githubusercontent.com/17954109/79108452-a66d1100-7d76-11ea-95e0-ecafcff65e87.jpg)
Is it what you want ? (i don't play enough :p)

**Comment by TheUntamed** [comment]
yes. That should work
