### ISSUE TITLE
[1.15.2] Item tag

### ISSUE THREAD

**Issue by TheUntamed** [Corail31/woodcutter#14]
First of: sorry for the issue spam.
It would be neat if you could add a item tag to the woodcutters. Something like 

> <tag:corail_woodcutter:woodcutter>

I mean i could add the tag myself using scripts but it would be cleaner if they already had one.
(They should also have a block tag.)

**Comment by Corail31** [comment]
@TheUntamed would it be enough with vanilla ones in ?

**Comment by TheUntamed** [comment]
Is there a vanilla tags for woodcutter? Or do you mean only a tag on woodcutter made with vanilla planks?

**Comment by Corail31** [comment]
What is your real objective behind this request ? i added a tag block/item for vanilla_woodcutters and one for woodcutters (but containing only the vanilla ones as my mod doesn't depend on the supported mods)

**Comment by TheUntamed** [comment]
It doesn't matter if the woodcutter is vanilla or based on another mods wood.
The tag I wanted is a general tag that is the same for all woodcutters. Then i can for example do something like:
`<tag:corail_woodcutter:woodcutter>.items` which gives me all woodcutters.
The tag just tells the game that all blocks/items with that tag are woodcutters.

**Comment by Corail31** [comment]
What i mean is it would be better to add yourself with json the "modded woodcutters" in the tag over the default ones added with this change, if you use one of the supported mod (bop/midnight)

**Comment by TheUntamed** [comment]
yeah maybe. Then i will add them myself.

**Comment by Corail31** [comment]
@TheUntamed contact me on curse for a version to make your tests ;)

**Comment by Corail31** [comment]
to check all is how you asked

**Comment by TheUntamed** [comment]
ah ok. (Same for me)

**Comment by TheUntamed** [comment]
Tests were successful. Names and JEI usage works perfectly.

**Comment by TheUntamed** [comment]
Did you remove the `<tag:corail_woodcutter:allowed_items>` tag?

**Comment by Corail31** [comment]
Yes it's, this list was only used for the shift click action and is no more needed.
