### ISSUE TITLE
not an issue just a request

### ISSUE THREAD

**Issue by MilitaryFool** [Corail31/woodcutter#15]
Could you port this to work for 1.12.2? I have a mod that does it for the stone cutter but not this, I loved using your woodcutter mod in 1.15 and wanted to use it in 1.12 with tinkers construct

**Comment by Corail31** [comment]
Hello MilitaryFool,
I think i'll disappoint you but i don't plan to port this mod to 1.12.2
For me, the 1.12.2 version got a long life, but what is in the more recent versions is really better for modders, and it's more time to go in theses versions.

**Comment by MilitaryFool** [comment]
Ok, I just wanted to know if you'd do it that's fine, thank you
