### ISSUE TITLE
crash on Fabric 1.15.2 version 1.0.1

### ISSUE THREAD

**Issue by Dragonracer1973** [Corail31/woodcutter#16]
[crash-2020-04-24_18.57.00-client.txt](https://github.com/Corail31/woodcutter/files/4532259/crash-2020-04-24_18.57.00-client.txt)

**Comment by Dragonracer1973** [comment]
got this after a couple of updates to a few mods I have installed and updated (namely Mechanized, which I thought was the culprit) that dev read the report (better than me) and pointed me in your direection

**Comment by Corail31** [comment]
You should use the fabric api version provided in the changelog, if they make breaking changes, this doesn't mean i would update it, being mainly a mod for forge and having enough with the breaking changes of snapshot 1.16.

**Comment by Corail31** [comment]
@Dragonracer1973 it seems on my side as i used the implementation so i'll fix it.

**Comment by Corail31** [comment]
fixed in 1.0.2 for 1.15.2

**Comment by Dragonracer1973** [comment]
thank you, I really enjoy this mod
