### ISSUE TITLE
Broken JEI Compat

### ISSUE THREAD

**Issue by WenXin20** [Corail31/woodcutter#17]
`Forge v31.1.61`
`Minecraft v1.15.2`
`Woodcutter v1.1.2`
`JEI v6.0.0.4`

JEI recently had an update that added the Stonecutter recipes to JEI, which seems to have broken the Sawmill's recipe preview for JEI. [Error Log](https://gist.github.com/WenXin20/b4becc18c2cfd2e7a61bce97e35d51c9)

**Comment by Corail31** [comment]
Please edit your issue WenXin20...
The fact is JEI didn't yet have this feature and now has it, but it's also a config option, so you just need to disable it in config.

**Comment by WenXin20** [comment]
Yes, I'm aware that stone cutting was not previously in JEI. I made the report because the sawmill recipe previews are not working at all.

**Comment by Corail31** [comment]
If this message is not edited, it'll be suppressed without any additional consideration.
It's not how to post logs. You are not forced to update to the latest JEI on the same time.

**Comment by WenXin20** [comment]
> Please edit your issue WenXin20....

You were not clear on what to even edit in the first place. 

And that is literally the only error in the entire log, but here is a link to it instead: [Error Log](https://gist.github.com/WenXin20/b4becc18c2cfd2e7a61bce97e35d51c9)
And I know that I don't have to update JEI. I made this issue so that you were actually aware of it and could fix it.

**Comment by Corail31** [comment]
Thanks WenXin20, it's only that logs copy/paste like this looks more like "trash message".
I'll make a release to remove this category :)

**Comment by Corail31** [comment]
solved in 1.1.3 for 1.15.2

**Comment by WenXin20** [comment]
Thanks!
