### ISSUE TITLE
Change recipes to accept tags

### ISSUE THREAD

**Issue by WenXin20** [Corail31/woodcutter#2]
For 1.14, some recipes can be changed to accept tags instead, specifically logs.

For example, instead of using the item `minecraft:oak_log` for the Woodcutter recipes, instead use the tag `minecraft:oak_logs`.

This will allow the log and it's corresponding wood and stripped logs & wood blocks to be used to craft items, just like in a crafting table.

**Comment by Corail31** [comment]
Hi WenXin20,
It looks to be a good idea.

**Comment by WenXin20** [comment]
Biomes O' Plenty also has tags for it's logs, such as `biomesoplenty:palm_logs`.

**Comment by Corail31** [comment]
Do you really know mods adding new biomeoplenty palm log?

**Comment by WenXin20** [comment]
Biomes O' Plenty has 4 different variants for it's logs, so there's the Palm Log, Palm Wood, Stripped Palm Log, & Stripped Palm Wood. Changing it to accept tags would mean any of those logs could be used in the Woodcutter, otherwise only the Palm Log will work.

**Comment by Corail31** [comment]
Ah yes, thanks for the precision :) I'll change it.
