### ISSUE TITLE
Is there a fabric 1.15.2 version

### ISSUE THREAD

**Issue by DanShu15** [Corail31/woodcutter#21]
I'm really sorry if it's there and I'm just missing it, but I can't seem to find a 1.15.2 version for Fabric. I just noticed it wasn't working and realized I had the forge 1.1.3-1.15.2 version installed on my server with the 1.0.4 corail addon

**Comment by Corail31** [comment]
Hi Danshu15, the link is this [one](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter/files/2941158).

**Comment by DanShu15** [comment]
I love you
