### ISSUE TITLE
Scrollbar can get stuck

### ISSUE THREAD

**Issue by WenXin20** [Corail31/woodcutter#3]
`Minecraft v1.14.4`
`Forge v28.1.109`
`Woodcutter v1.1.0`

Sometimes the scrollbar can get stuck at the bottom, which leaves some recipes unreachable.

- To replicate, 1st place an item in the input slot that requires you to scroll to the bottom to see the last recipe, such as an oak log. 
- Then pick up another item that does not need any scrolling, such as an oak plank, and swap it with the current item in the input slot. 
- The top rows will now be locked out because the scrollbar is locked. 
- The bug won't happen if you take the item out first before placing a different item in the slot.
- This is a bug with the Stonecutter too unfortunately.

**Comment by Corail31** [comment]
If it's a bug in the stonecutter, you should report it to Forge to fix it, so i could benefit from the fix too ;)
Coders are lazy :p

**Comment by WenXin20** [comment]
Ok, I'll try that.
