### ISSUE TITLE
Shift-clicking doesn't always work

### ISSUE THREAD

**Issue by WenXin20** [Corail31/woodcutter#4]
`Minecraft v1.14.4`
`Forge v28.1.109`
`Woodcutter v1.1.0`

From what I can tell, only logs & planks can be shift-clicked into the input slot. But some items, if given a recipe through Crafttweaker, can't be shift-clicked into the input slot. 
An example is the Dreamwood planks from Botania, after giving it a recipe output, it still can't be shift-clicked into the input slot.

**Comment by Corail31** [comment]
Hi WenXin20,
as you imagine, it's called woodcutter because it accepts wood/log.
The shift-click should work if you add them in the adequate tag : minecraft:planks or minecraft:logs.

**Comment by WenXin20** [comment]
I was wondering if that was the case. Midnight planks also can't be shift-clicked into the input slot, probably because they aren't tagged.
