### ISSUE TITLE
Varient support for Upgrade Aquatic

### ISSUE THREAD

**Issue by IronPiston** [Corail31/woodcutter#5]
[Upgrade Aquatic](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic) adds a single new type of wood, Driftwood, and various products using Driftwood. Similar to Biomes O' Plenty and Midnight, could you add a driftwood woodcutter?

**Comment by Corail31** [comment]
The mod "Upgrade Aquatic" can add itself the recipes for woodcutter.
This is how the mod is supposed to be used (biomesoplenty & midnight being some exceptions as i follow their changes)

**Comment by IronPiston** [comment]
Sorry I wasn't clear, I meant adding a woodcutter using the driftwood texture. I understand if you don't want to add in the actual driftwood slabs, fence, etc.

**Comment by Corail31** [comment]
@IronPiston i loaded the mod alone, and i got a spam of errors about things not existing block, tags, the fr language is not correctly formatted. So i'll wait their release to be more stable before adding it.
