### ISSUE TITLE
 Reference map 'corail_woodcutter-refmap.json' for corail_woodcutter.mixins.json could not be read.

### ISSUE THREAD

**Issue by serpi90** [Corail31/woodcutter#8]
Log reports the following error:

Reference map 'corail_woodcutter-refmap.json' for corail_woodcutter.mixins.json could not be read. If this is a development environment you can ignore this message.

Minecraft: 1.15.2
Fabric 0.7.6+build.180
Mod version corail_woodcutter-fabric-1.0.0-1.15.1

**Comment by Corail31** [comment]
Hi serpi90, the fabric version is more a test as i'm not a lot informed about it.
In my workspace, it says it creates it when missing, so i didn't take a lot of attention about it.
Does it prevent the launch ? as i tested to launch both 1.15.1 & 1.15.2 before publishing it.

**Comment by serpi90** [comment]
It's just a warning, the mood works afaik. Sorry for not mentioning it
before.

**Comment by Corail31** [comment]
No, it's fine and perhaps a modder more used with Fabric will fall on this message and give an indication ;)
