### ISSUE TITLE
Any chance to support Traverse and Terrestria wood types?

### ISSUE THREAD

**Issue by Trnrr** [Corail31/woodcutter#9]
Traverse: https://www.curseforge.com/minecraft/mc-mods/traverse
Terrestria: https://www.curseforge.com/minecraft/mc-mods/terrestria/

**Comment by Corail31** [comment]
Hi Trnrr,
The objective of the mod is not to create recipes for others mods as it would mean to follow any block they would change.
Normally, they would be intended to be added by the mods themselves like for stonecutter but, unlike in forge, i don't think Fabric has conditional recipes allowing to load them only if a mod is present, to not require a hard dependency on woodcutter (but i'm far to be fully informed about Fabric)

**Comment by Trnrr** [comment]
Hmm there is a way to do it since some fabric mods do. I have no clue how though. Is it possible to manually add the new ones in a datapack? If so I can just do that.

**Comment by Corail31** [comment]
In any case, the recipes need to be in their mod (and so the hook too or in fabric api)

**Comment by Trnrr** [comment]
I'm creating a small survival orientated modpack so I can just include the new recipes in the datapack we already ship it with. Thank you
